version: "3.8"
services:
    # Mysql database container
    db:
        build: ./db
        container_name: mysqldb
        restart: always
        volumes:
            - books-app-data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=admin
            - TZ=Europe/Sofia
        networks:
            - books-app

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: pma
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - books-app

networks:
    books-app:

volumes:
    books-app-data:
